// Dunyo valyutalari ro'yxati — kod, o'zbekcha nomi, bayroq uchun davlat kodi (ISO 3166-1 alpha-2)
const CURRENCIES = [
  { code: "UZS", uz: "O'zbek so'mi", country: "UZ" },
  { code: "USD", uz: "AQSh dollari", country: "US" },
  { code: "EUR", uz: "Yevro", country: "EU" },
  { code: "RUB", uz: "Rossiya rubli", country: "RU" },
  { code: "GBP", uz: "Angliya funt sterlingi", country: "GB" },
  { code: "JPY", uz: "Yaponiya iyenasi", country: "JP" },
  { code: "CNY", uz: "Xitoy yuani", country: "CN" },
  { code: "KRW", uz: "Janubiy Koreya voni", country: "KR" },
  { code: "TRY", uz: "Turkiya lirasi", country: "TR" },
  { code: "KZT", uz: "Qozog'iston tengesi", country: "KZ" },
  { code: "KGS", uz: "Qirg'iziston somi", country: "KG" },
  { code: "TJS", uz: "Tojikiston somonisi", country: "TJ" },
  { code: "TMT", uz: "Turkmaniston manati", country: "TM" },
  { code: "AFN", uz: "Afg'oniston afg'onisi", country: "AF" },
  { code: "AZN", uz: "Ozarbayjon manati", country: "AZ" },
  { code: "AMD", uz: "Armaniston drami", country: "AM" },
  { code: "GEL", uz: "Gruziya larisi", country: "GE" },
  { code: "BYN", uz: "Belarus rubli", country: "BY" },
  { code: "UAH", uz: "Ukraina grivnasi", country: "UA" },
  { code: "MDL", uz: "Moldova leyi", country: "MD" },
  { code: "PLN", uz: "Polsha zlotiysi", country: "PL" },
  { code: "CZK", uz: "Chexiya kronasi", country: "CZ" },
  { code: "HUF", uz: "Vengriya forinti", country: "HU" },
  { code: "RON", uz: "Ruminiya leyi", country: "RO" },
  { code: "BGN", uz: "Bolgariya levi", country: "BG" },
  { code: "HRK", uz: "Xorvatiya kunasi", country: "HR" },
  { code: "RSD", uz: "Serbiya dinori", country: "RS" },
  { code: "CHF", uz: "Shveytsariya franki", country: "CH" },
  { code: "SEK", uz: "Shvetsiya kronasi", country: "SE" },
  { code: "NOK", uz: "Norvegiya kronasi", country: "NO" },
  { code: "DKK", uz: "Daniya kronasi", country: "DK" },
  { code: "ISK", uz: "Islandiya kronasi", country: "IS" },
  { code: "CAD", uz: "Kanada dollari", country: "CA" },
  { code: "AUD", uz: "Avstraliya dollari", country: "AU" },
  { code: "NZD", uz: "Yangi Zelandiya dollari", country: "NZ" },
  { code: "SGD", uz: "Singapur dollari", country: "SG" },
  { code: "HKD", uz: "Gonkong dollari", country: "HK" },
  { code: "TWD", uz: "Tayvan dollari", country: "TW" },
  { code: "THB", uz: "Tailand bati", country: "TH" },
  { code: "MYR", uz: "Malayziya ringgiti", country: "MY" },
  { code: "IDR", uz: "Indoneziya rupiyasi", country: "ID" },
  { code: "PHP", uz: "Filippin pesosi", country: "PH" },
  { code: "VND", uz: "Vyetnam dongi", country: "VN" },
  { code: "INR", uz: "Hindiston rupiyasi", country: "IN" },
  { code: "PKR", uz: "Pokiston rupiyasi", country: "PK" },
  { code: "BDT", uz: "Bangladesh takasi", country: "BD" },
  { code: "LKR", uz: "Shri-Lanka rupiyasi", country: "LK" },
  { code: "NPR", uz: "Nepal rupiyasi", country: "NP" },
  { code: "MMK", uz: "Myanma kyati", country: "MM" },
  { code: "KHR", uz: "Kambodja rieli", country: "KH" },
  { code: "LAK", uz: "Laos kipi", country: "LA" },
  { code: "MNT", uz: "Mongoliya tugriki", country: "MN" },
  { code: "AED", uz: "BAA dirhami", country: "AE" },
  { code: "SAR", uz: "Saudiya Arabistoni riyoli", country: "SA" },
  { code: "QAR", uz: "Qatar riyoli", country: "QA" },
  { code: "KWD", uz: "Kuvayt dinori", country: "KW" },
  { code: "BHD", uz: "Bahrayn dinori", country: "BH" },
  { code: "OMR", uz: "Ummon riyoli", country: "OM" },
  { code: "JOD", uz: "Iordaniya dinori", country: "JO" },
  { code: "ILS", uz: "Isroil shekeli", country: "IL" },
  { code: "LBP", uz: "Livan funti", country: "LB" },
  { code: "IQD", uz: "Iroq dinori", country: "IQ" },
  { code: "IRR", uz: "Eron riyoli", country: "IR" },
  { code: "SYP", uz: "Suriya funti", country: "SY" },
  { code: "YER", uz: "Yaman riyoli", country: "YE" },
  { code: "EGP", uz: "Misr funti", country: "EG" },
  { code: "MAD", uz: "Marokash dirhami", country: "MA" },
  { code: "DZD", uz: "Jazoir dinori", country: "DZ" },
  { code: "TND", uz: "Tunis dinori", country: "TN" },
  { code: "LYD", uz: "Liviya dinori", country: "LY" },
  { code: "NGN", uz: "Nigeriya nayrasi", country: "NG" },
  { code: "GHS", uz: "Gana sedisi", country: "GH" },
  { code: "KES", uz: "Keniya shillingi", country: "KE" },
  { code: "TZS", uz: "Tanzaniya shillingi", country: "TZ" },
  { code: "UGX", uz: "Uganda shillingi", country: "UG" },
  { code: "ETB", uz: "Efiopiya biri", country: "ET" },
  { code: "ZAR", uz: "JAR randi", country: "ZA" },
  { code: "XOF", uz: "G'arbiy Afrika franki", country: "SN" },
  { code: "XAF", uz: "Markaziy Afrika franki", country: "CM" },
  { code: "MZN", uz: "Mozambik metikali", country: "MZ" },
  { code: "ZMW", uz: "Zambiya kvachasi", country: "ZM" },
  { code: "AOA", uz: "Angola kvanzasi", country: "AO" },
  { code: "BRL", uz: "Braziliya reali", country: "BR" },
  { code: "ARS", uz: "Argentina pesosi", country: "AR" },
  { code: "MXN", uz: "Meksika pesosi", country: "MX" },
  { code: "CLP", uz: "Chili pesosi", country: "CL" },
  { code: "COP", uz: "Kolumbiya pesosi", country: "CO" },
  { code: "PEN", uz: "Peru soli", country: "PE" },
  { code: "UYU", uz: "Urugvay pesosi", country: "UY" },
  { code: "BOB", uz: "Boliviya bolivianosi", country: "BO" },
  { code: "PYG", uz: "Paragvay guaranisi", country: "PY" },
  { code: "VES", uz: "Venesuela boliviyari", country: "VE" },
  { code: "GTQ", uz: "Gvatemala ketsali", country: "GT" },
  { code: "CRC", uz: "Kosta-Rika koloni", country: "CR" },
  { code: "PAB", uz: "Panama balboasi", country: "PA" },
  { code: "DOP", uz: "Dominikana pesosi", country: "DO" },
  { code: "JMD", uz: "Yamayka dollari", country: "JM" },
  { code: "TTD", uz: "Trinidad va Tobago dollari", country: "TT" },
  { code: "BSD", uz: "Bagama dollari", country: "BS" },
  { code: "BBD", uz: "Barbados dollari", country: "BB" },
  { code: "BZD", uz: "Beliz dollari", country: "BZ" },
  { code: "HTG", uz: "Gaiti gourdi", country: "HT" },
  { code: "HNL", uz: "Gonduras lempirasi", country: "HN" },
  { code: "NIO", uz: "Nikaragua kordobasi", country: "NI" },
  { code: "XCD", uz: "Sharqiy Karib dollari", country: "AG" },
  { code: "FJD", uz: "Fiji dollari", country: "FJ" },
  { code: "PGK", uz: "Papua-Yangi Gvineya kinasi", country: "PG" },
  { code: "WST", uz: "Samoa talasi", country: "WS" },
  { code: "TOP", uz: "Tonga paangasi", country: "TO" },
  { code: "SBD", uz: "Solomon oroli dollari", country: "SB" },
  { code: "VUV", uz: "Vanuatu vatusi", country: "VU" },
  { code: "XPF", uz: "Tinch okeani franki", country: "PF" },
  { code: "MOP", uz: "Makao patakasi", country: "MO" },
  { code: "BND", uz: "Bruney dollari", country: "BN" },
  { code: "MVR", uz: "Maldiv rufiyasi", country: "MV" },
  { code: "BTN", uz: "Butan ngultrumi", country: "BT" },
  { code: "SCR", uz: "Seyshel rupiyasi", country: "SC" },
  { code: "MUR", uz: "Mavrikiy rupiyasi", country: "MU" },
  { code: "MGA", uz: "Madagaskar ariarisi", country: "MG" },
  { code: "NAD", uz: "Namibiya dollari", country: "NA" },
  { code: "BWP", uz: "Botsvana pulasi", country: "BW" },
  { code: "SZL", uz: "Svazilend lilangenisi", country: "SZ" },
  { code: "LSL", uz: "Lesoto lotisi", country: "LS" },
  { code: "MWK", uz: "Malavi kvachasi", country: "MW" },
  { code: "RWF", uz: "Ruanda franki", country: "RW" },
  { code: "BIF", uz: "Burundi franki", country: "BI" },
  { code: "DJF", uz: "Djibuti franki", country: "DJ" },
  { code: "SOS", uz: "Somali shillingi", country: "SO" },
  { code: "SDG", uz: "Sudan funti", country: "SD" },
  { code: "SSP", uz: "Janubiy Sudan funti", country: "SS" },
  { code: "ERN", uz: "Eritreya nakfasi", country: "ER" },
  { code: "GMD", uz: "Gambiya dalasisi", country: "GM" },
  { code: "GNF", uz: "Gvineya franki", country: "GN" },
  { code: "SLL", uz: "Syerra-Leone leoni", country: "SL" },
  { code: "LRD", uz: "Liberiya dollari", country: "LR" },
  { code: "CVE", uz: "Kabo-Verde eskudosi", country: "CV" },
  { code: "STN", uz: "San-Tome va Prinsipi dobrasi", country: "ST" },
  { code: "KMF", uz: "Komor franki", country: "KM" },
  { code: "CDF", uz: "Kongo franki", country: "CD" },
  { code: "XDR", uz: "Maxsus qarz olish huquqi (SDR)", country: "UN" },
];

// Ba'zi kodlar rasmiy ISO davlat kodiga to'g'ri kelmaydi (masalan EUR, XOF), shuning
// uchun ular uchun bayroq chiqmasa umumiy belgidan foydalaniladi.
function getFlagEmoji(countryCode) {
  if (!countryCode || countryCode === "EU") return "🇪🇺";
  if (countryCode === "UN") return "🌐";
  try {
    return countryCode
      .toUpperCase()
      .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
  } catch (e) {
    return "💱";
  }
}
